export const CURRENCY_TO_COUNTRY: Record<string, string> = {
    USD: 'us',
    EUR: 'eu',
    GBP: 'gb',
    JPY: 'jp',
    AUD: 'au',
    CAD: 'ca',
    CHF: 'ch',
    CNY: 'cn',
    HKD: 'hk',
    NZD: 'nz',
    SEK: 'se',
    KRW: 'kr',
    SGD: 'sg',
    NOK: 'no',
    MXN: 'mx',
    INR: 'in',
    RUB: 'ru',
    ZAR: 'za',
    TRY: 'tr',
    BRL: 'br',
    TWD: 'tw',
    DKK: 'dk',
    PLN: 'pl',
    THB: 'th',
    IDR: 'id',
    HUF: 'hu',
    CZK: 'cz',
    ILS: 'il',
    CLP: 'cl',
    PHP: 'ph',
    AED: 'ae',
    COP: 'co',
    SAR: 'sa',
    MYR: 'my',
    RON: 'ro',
    VND: 'vn',
    ARS: 'ar',
    BGN: 'bg',
    ISK: 'is',
    HRK: 'hr',
    BHD: 'bh',
    KWD: 'kw',
    QAR: 'qa',
    EGP: 'eg',
    OMR: 'om',
    JOD: 'jo',
    LKR: 'lk',
    PKR: 'pk',
    KZT: 'kz',
    PEN: 'pe',
};

export const getFlagUrl = (currency: string): string | null => {
    const countryCode = CURRENCY_TO_COUNTRY[currency.toUpperCase()];
    if (!countryCode) return null;
    return `https://flagcdn.com/w40/${countryCode.toLowerCase()}.png`;
};
